// WebVM Configuration - Auto-generated by GitHub Actions
export const webvmConfig = {
  diskImageUrl: "wss://disks.webvm.io/debian_large_20230522_5044875331.ext2",
  diskImageType: "cloud",
  memorySize: 512 * 1024 * 1024,
  vgaMemory: 16 * 1024 * 1024,
  networkEnabled: false
};
